/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fsantoro
 */
public class ACQ2106_435SC_3STSetup extends DeviceSetup {

    /**
     * Creates new form ACQ2106_435SC_3STSetup
     */
    public ACQ2106_435SC_3STSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceButtons1 = new DeviceButtons();
        jPanel1 = new javax.swing.JPanel();
        deviceField1 = new DeviceField();

        setDeviceProvider("172.20.240.104:9998");
        setDeviceTitle("Signal Conditioning Device");
        setDeviceType("acq2106_435sc_3st");
        setHeight(500);
        setUpdateEvent("");
        setWidth(800);
        getContentPane().add(deviceButtons1, java.awt.BorderLayout.PAGE_END);

        deviceField1.setIdentifier("");
        deviceField1.setLabelString("Device IP");
        deviceField1.setNumCols(20);
        deviceField1.setOffsetNid(1);
        deviceField1.setTextOnly(true);
        jPanel1.add(deviceField1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DeviceButtons deviceButtons1;
    private DeviceField deviceField1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
